Initial bulk
SAP/scimono pull request #150
Opened 2021-07-19 08:10 UTC by karaimin

2021-07-21 10:25 UTC, ElisavetaTodorova approved these changes

2021-07-21 12:01 UTC, VladislavStefanov requested changes

2021-07-21 12:24 UTC, VladislavStefanov commented on scimono-server/src/main/java/com/sap/scimono/entity/bulk/RequestOperation.java
> +          data = JSON_MAPPER.treeToValue(rawData, User.class);
I just saw it being handled in ResourcePreProcessor. Ignore this comment.

2021-07-22 13:43 UTC, karaimin commented on scimono-server/src/main/java/com/sap/scimono/entity/bulk/RequestOperation.java
> +      throw new InternalScimonoException(String.format("wrong data format for bulk operation with id: %s", super.getBulkId()));
Actually this should be ensured on validation level

2021-07-22 13:43 UTC, karaimin commented on scimono-server/src/main/java/com/sap/scimono/api/Bulk.java
> +      int payloadSize = bulkSetting.getMaxPayloadSize();
After discussions we decided to not validate the payload size setting

2021-07-22 14:13 UTC, VladislavStefanov approved these changes

2021-07-22 14:46 UTC, merged